### ISSUE TITLE
Recommended file extension for `brokJSON` files?

### ISSUE THREAD

**Issue by SeaDude** [simonhuwiler/brokJSON_py#1]
Hello,
What file format should converted (from geojson to brokjson) files be stored in?
Thanks

**Comment by simonhuwiler** [comment]
Hi
I use mostly `*.brokjson` but you could use `*.json` as well.

**Comment by SeaDude** [comment]
Coo. I went with `.json` as I can use `json.loads(fileName)` to validate.
